
inicio
     INTEIRO Ano_Nascimento, Ano_atual, idade, anos_2050
     
     ESCREVER "Informe o ano atual: "
     LER ano_atual
     
     ESCREVER "Informe o ano de seu nascimento: "
     LER ano_nascimento
     
     idade <- ano_atual - ano_nascimento
     
     ESCREVER "Sua idade é: ", idade
     
     anos_2050 <- 2050 - ano_nascimento
     
     ESCREVER "\nEsta será sua idade em 2050: ", anos_2050
	
fim
