
inicio
	Real Salario, Percentual_aumento, aumento, novo_sal

      Escrever "Entre com o seu salario: "
      ler salario
      
      Escrever "Entre com o Percentual de aumento: "
      Ler percentual_aumento
      
      
      novo_sal <- salario * (Percentual_aumento +1) / 10
      
      Escrever "Este é seu novo salario: ", novo_sal
      
      aumento <- novo_sal - salario
     
      Escrever "\nEste é o seu aumento: ", aumento 
fim
